AWSTemplateFormatVersion: 2010-09-09
Description:  This template deploys an EC2 with VPC and security group in either us-east-1 or us-west-2,
 with a pair of public and private subnets spread across two Availability Zones. It deploys an internet gateway, 
 with a default route on the public subnets, a recommended Linux t3.large Instance with Security Group with open HTTP access. 


Mappings:
  RegionMap:
    us-east-1:
     "AMI": "ami-0742b4e673072066f"
    us-west-2:
     "AMI": "ami-0518bb0e75d3619ca"

Resources:

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Pinterest Project

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Pinterest Project

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Pinterest Project Public Subnet (AZ1)

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Pinterest Project Public Subnet (AZ2)

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs  '' ]
      CidrBlock: 10.0.11.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Pinterest Project Private Subnet (AZ1)

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs  '' ]
      CidrBlock: 10.0.12.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: Pinterest Project Private Subnet (AZ2)

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Pinterest Project Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet2
      
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP from 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9090"
          ToPort: "9090"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "3000"
          ToPort: "3000"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "9100"
          ToPort: "9100"
          CidrIp: 0.0.0.0/0        
        - IpProtocol: tcp
          FromPort: "2181"
          ToPort: "2181"
          CidrIp: 0.0.0.0/0     
        - IpProtocol: tcp
          FromPort: "7077"
          ToPort: "7077"
          CidrIp: 0.0.0.0/0            
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0            
        - IpProtocol: tcp
          FromPort: "9042"
          ToPort: "9042"
          CidrIp: 0.0.0.0/0           
        - IpProtocol: tcp
          FromPort: "8000"
          ToPort: "8000"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8793"
          ToPort: "8793"
          CidrIp: 0.0.0.0/0  
        - IpProtocol: tcp
          FromPort: "5432"
          ToPort: "5432"
          CidrIp: 0.0.0.0/0           
        - IpProtocol: tcp
          FromPort: "9091"
          ToPort: "9091"
          CidrIp: 0.0.0.0/0            
          
      VpcId: !Ref VPC 
      
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
        -
          DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: 24
            VolumeType: gp2
      IamInstanceProfile: s3-admin
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI]
      InstanceType: t3.large
      KeyName: pin_app
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds: 
        - !Ref WebServerSecurityGroup
      Tags:
       - Key: Name
         Value: Pinterest Project EC2     
      UserData:
        Fn::Base64: !Sub |
            #!/bin/sh
            
            echo "export PATH=/usr/local/bin:$PATH;" >> /home/ec2-user/.bashrc
            sudo yum update -y 
            sudo yum upgrade -y
            
            # install docker engine
            sudo amazon-linux-extras install docker -y
            sudo service docker start
            sudo systemctl enable docker
            sudo usermod -a -G docker ec2-user
            
            # instal docker-compose
            sudo wget https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)
            sudo mv docker-compose-$(uname -s)-$(uname -m) /usr/local/bin/docker-compose
            sudo chmod -v +x /usr/local/bin/docker-compose
            
            
            # install wget
            sudo yum install wget -y
            
            # install git
            sudo yum install git -y
            
            # Install java
            sudo wget https://javadl.oracle.com/webapps/download/AutoDL?BundleId=243712_61ae65e088624f5aaa0b1d2d801acb16
            sudo tar -xvf AutoDL?BundleId=243712_61ae65e088624f5aaa0b1d2d801acb16 -C /home/ec2-user/ --remove-files
            sudo mv /home/ec2-user/jdk1.8.0_271 /home/ec2-user/java
            sudo rm -f AutoDL?BundleId=243712_61ae65e088624f5aaa0b1d2d801acb16

            
            # sudo yum install java-1.8.0-openjdk -y 
            
            
            # sudo git clone
            #   https://git-codecommit.us-east-1.amazonaws.com/v1/repos/pinterest_project
            sudo git clone https://github.com/huo1m1w1/pinterest-data-processing-pipeline584.git
            pip3 install -r pinterest-data-processing-pipeline584/requirements.txt
            
            # Download kafka package
            sudo wget https://downloads.apache.org/kafka/3.2.3/kafka_2.13-3.2.3.tgz
            sudo wget https://downloads.apache.org/kafka/3.2.3/kafka_2.13-3.2.3.tgz.asc
            sudo wget https://downloads.apache.org/kafka/KEYS
            
            # verifying kafka
            sudo gpg --import KEYS
            sudo gpg --verify kafka_2.13-3.2.3.tgz.asc kafka_2.13-3.2.3.tgz
            sudo tar -xzf kafka_2.13-3.2.3.tgz -C /home/ec2-user/ --remove-files
            sudo mv /home/ec2-user/kafka_2.13-3.2.3 /home/ec2-user/kafka
            sudo rm kafka_2.13-3.2.3.tgz
            sudo rm kafka_2.13-3.2.3.tgz.asc
            sudo rm -f KEYS
            

            
            
            # insatll spark
            sudo wget https://dlcdn.apache.org/spark/spark-3.2.3/spark-3.2.3-bin-hadoop3.2.tgz
            sudo wget https://dlcdn.apache.org/spark/spark-3.2.3/spark-3.2.3-bin-hadoop3.2.tgz.asc
            sudo wget https://downloads.apache.org/spark/KEYS
            
            
            # verify spark package
            sudo gpg --import KEYS
            sudo gpg --verify spark-3.2.3-bin-hadoop3.2.tgz.asc spark-3.2.3-bin-hadoop3.2.tgz
            sudo tar -xzf spark-3.2.3-bin-hadoop3.2.tgz -C /home/ec2-user/  --remove-files
            sudo mv /home/ec2-user/spark-3.2.3-bin-hadoop3.2 /home/ec2-user/spark
            sudo rm spark-3.2.3-bin-hadoop3.2.tgz.asc
            sudo rm -f KEYS
            sudo rm -f spark-3.2.3-bin-hadoop3.2.tgz
        
            
            
            # install decendencies
            sudo wget https://repo1.maven.org/maven2/com/datastax/spark/spark-cassandra-connector_2.12/3.2.0/spark-cassandra-connector_2.12-3.2.0.jar -P /home/ec2-user/spark/jars
            sudo wget https://repo1.maven.org/maven2/software/amazon/awssdk/bundle/2.15.0/bundle-2.15.0.jar -P /home/ec2-user/spark/jars
            sudo wget https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.2.3/spark-sql-kafka-0-10_2.12-3.2.3.jar -P /home/ec2-user/spark/jars
            sudo wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.2.3/hadoop-aws-3.2.3.jar -P /home/ec2-user/spark/jars
            
            # install cassandra
            sudo wget https://downloads.apache.org/cassandra/4.0.7/apache-cassandra-4.0.7-bin.tar.gz
            sudo wget https://downloads.apache.org/cassandra/4.0.7/apache-cassandra-4.0.7-bin.tar.gz.asc
            sudo wget https://downloads.apache.org/cassandra/KEYS
            sudo gpg --import KEYS
            sudo gpg --verify apache-cassandra-4.0.7-bin.tar.gz.asc apache-cassandra-4.0.7-bin.tar.gz
            tar -xvzf apache-cassandra-4.0.7-bin.tar.gz -C /home/ec2-user/ --remove-files
            sudo mv /home/ec2-user/apache-cassandra-4.0.7 /home/ec2-user/cassandra
            sudo mkdir /home/ec2-user/cassandra/etc
            sudo rm apache-cassandra-4.0.7-bin.tar.gz.asc            
            sudo rm KEYS
            sudo rm -f apache-cassandra-4.0.7-bin.tar.gz            
            
            # install airflow
            sudo wget https://dlcdn.apache.org/airflow/2.5.1/apache-airflow-2.5.1-source.tar.gz
            sudo wget https://dlcdn.apache.org/airflow/2.5.1/apache-airflow-2.5.1-source.tar.gz.asc
            sudo wget https://downloads.apache.org/airflow/KEYS
            sudo gpg --import KEYS
            sudo gpg --verify apache-airflow-2.5.1-source.tar.gz.asc apache-airflow-2.5.1-source.tar.gz
            tar -xvzf apache-airflow-2.5.1-source.tar.gz -C /home/ec2-user/ --remove-files
            sudo mv /home/ec2-user/apache-airflow-2.5.1 /home/ec2-user/airflow
            sudo rm apache-airflow-2.5.1-source.tar.gz.asc            
            sudo rm KEYS
            sudo rm -f apache-airflow-2.5.1-source.tar.gz   
              
            # pip3 install 'apache-airflow[postgres]==2.5.1' --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.1/constraints-3.7.txt"
            airflow db init
            airflow users create --username admin --firstname Michael --lastname Huo --role Admin --email m.h@apache.airflow.org
            
            # install jmx_export
            sudo wget https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.3.0/jmx_prometheus_javaagent-0.3.0.jar
            sudo wget https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/cassandra.yml
            
            echo 'JVM_OPTS="$JVM_OPTS -javaagent:'/jmx_prometheus_javaagent-0.3.0.jar=7070:/cassandra.yml'"' >> /home/ec2-user/cassandra/conf/cassandra-env.sh
            
            # install grafana
            sudo wget https://dl.grafana.com/enterprise/release/grafana-enterprise-9.3.0-1.x86_64.rpm
            sudo yum install grafana-enterprise-9.3.0-1.x86_64.rpm -y
            
            # install prometheus
            sudo wget https://github.com/prometheus/prometheus/releases/download/v2.0.0/prometheus-2.0.0.linux-amd64.tar.gz
            sudo tar -xzf prometheus-2.0.0.linux-amd64.tar.gz
            sudo rm -f prometheus-2.0.0.linux-amd64.tar.gz
            cat << EOF > /prometheus-2.0.0.linux-amd64/prometheus.yml
            global:
            scrape_interval: 10s
            evaluation_interval: 10s
            scrape_configs:
            - job_name: 'cassandra'
            static_configs:
              - targets:
                - localhost:7070
            
            - job_name: 'postgres'
            static_configs:
              - targets:
                - localhost:5432                  
            EOF

            # install scala sbt
            
            sudo wget http://downloads.typesafe.com/scala/2.11.6/scala-2.11.6.tgz
            sudo tar -xzvf scala-2.11.6.tgz
            sudo rm -rf scala-2.11.6.tgz

            cat << EOF >> /home/ec2-user/.bashrc
            export AIRFLOW_HOME=/home/ec2-user/airflow
            export PATH=$PATH:/home/ec2-user//home/ec2-user/airflow/bin
            export CASSANDRA_HOME=/home/ec2-user/cassandra
            export PATH=$PATH:/home/ec2-user//home/ec2-user/cassandra/bin
            export SPARK_HOME=/home/ec2-user/spark
            export PATH=$PATH:/home/ec2-user/spark/bin
            export JAVA_HOME=/home/ec2-user/java
            export PATH="$JAVA_HOME/bin:$PATH"
            export KAFKA_HOME=/home/ec2-user/kafka
            export PATH=$PATH:/home/ec2-user/kafka/bin
            export SCALA_HOME=/home/ec2-user/scala-2.11.6
            export PATH=$PATH:/home/ec2-user/scala-2.11.6/bin
            EOF
            
            source /home/ec2-user/.bashrc      
            
            # remove old Bintray repo file
            
            sudo rm -f /etc/yum.repos.d/bintray-rpm.repo
            sudo curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
            sudo mv sbt-rpm.repo /etc/yum.repos.d/
            sudo dnf install sbt                      

            
            # install Redis
            
            sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
            yum clean all
            sudo yum install redis -y
            
            # Start redis server            
            # sudo redis-server /etc/redis.conf  
            # install postgreSQL            
            # sudo amazon-linux-extras install postgresql14 postgresql-server -y
            
